server:
  address: localhost
  port: 8080
spring:
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/withsports?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename:
      - messages
      - errors
logging:
  level:
    org:
      hibernate:
        SQL: debug


cors:
  allowed-origins: '*'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true
  maxAge: 3600
